{{- $label := .Values.label | squote -}}
{{- $refresh := .Values.requeueAfterSeconds -}}
{{- $owner := .Values.owner -}}
{{- $path := .Values.path | squote -}}
{{- $namespace := .Values.namespace -}}
{{- $secretName := .Values.secretName -}}
{{- $secretKey := .Values.secretKey -}}
{{- $dqf := "{{" -}}
{{- $dqb := "}}" -}}
{{- $server := .Values.server | squote -}}
{{- $kustomizeEnabled := .Values.kustomize.enabled | default false -}}

{{- range $repo := .Values.repos }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ $repo.name }}-github'
  namespace: '{{ $namespace }}'
  annotations:
    app.kubernetes.io/name: '{{ $repo.name }}'
    app.kubernetes.io/managed-by: '{{ $.Release.Service }}'
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
  - pullRequest:
      github:
        owner: '{{ $owner }}'
        repo: '{{ $repo.name }}'
        labels:
        - {{ $label }}
        {{- if and ($secretName) ($secretKey) }}
        tokenRef:
          secretName: {{ $secretName }}
          key: {{ $secretKey }}
        {{- end }}
      requeueAfterSeconds: {{ $refresh }}
  template:
    metadata:
      name: '{{ $repo.name }}-{{ $dqf }}branch{{ $dqb }}-{{ $dqf }}number{{ $dqb }}'
      annotations:
        argocd.argoproj.io/head: '{{ $dqf }}head_sha{{ $dqb }}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      source:
        repoURL: 'https://github.com/{{ $owner }}/{{ $repo.name }}.git'
        targetRevision: '{{ $dqf }}head_sha{{ $dqb }}'
        {{- if $kustomizeEnabled }}
        kustomize:
          commonAnnotations:
            app.kubernetes.io/instance: '{{ $repo.name }}'
            app.kubernetes.io/past-of: {{ $label }}
            argocd.argoproj.io/head_sha: '{{ $dqf }}head_sha{{ $dqb }}'
          {{- range $i, $r := $repo.images }}
          {{- if eq $i 0 }}
          images:
          {{- end }}
          - {{ $r | indent 0 | squote }}
          {{- end }}
        {{- end }}
        path: {{ or $repo.path $path }}
      project: 'default'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
      destination:
        server: {{ $server }}
        namespace: '{{ $repo.name }}-{{ $dqf }}branch{{ $dqb }}-{{ $dqf }}number{{ $dqb }}'
{{- end }}
