{{- if and .Values.repos .Values.repos.github }}
{{- $github := .Values.github -}}
{{- $globals := .Values.globals -}}
{{- $name := .Values.name -}}
{{- $refresh := include "chart.refresh" . -}}
{{- $retryBackoffDuration := include "chart.retryBackoffDuration" . -}}
{{- $namespace := include "chart.namespace" . -}}
{{- $dqf := "{{" -}}
{{- $dqb := "}}" -}}
{{- $server := include "chart.server" . -}}
{{- $pr := contains "api.github.com" $github.api | ternary "https://github.com" $github.api -}}

{{- range $key, $repo := .Values.repos.github }}
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: '{{ required "A valid repo name is required" $repo.name | trunc 40 | trimSuffix "-" }}-github-{{ $name }}'
  namespace: {{ required "A valid namespace is required" $namespace | replace "." "-" }}
  labels:
    app.kubernetes.io/name: {{ $repo.name }}
    app.kubernetes.io/platform: 'github'
  annotations:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
spec:
  goTemplate: true
  {{- with $globals.goTemplateOptions }}
  goTemplateOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  syncPolicy:
    preserveResourcesOnDeletion: {{ $globals.preserveResourcesOnDeletion | default false }}
  generators:
  {{- if eq $server "all" }}
  - matrix:
      generators:
      - clusters: {}
      - {{ include "chart.githubGenerator" (dict "github" $github "globals" $globals "repo" $repo "refresh" $refresh) | nindent 8 | trim }}
  {{- else }}
  - {{ include "chart.githubGenerator" (dict "github" $github "globals" $globals "repo" $repo "refresh" $refresh) | nindent 4 | trim }}
  {{- end }}
  {{- $localRepoUrl := printf "https://github.com/%s/%s.git" $github.owner $repo.name -}}
  {{- $repoURL := coalesce $repo.repoUrl $localRepoUrl -}}
  {{- $externalLink := printf "%s/%s/%s/pull/%s .number %s" $pr $github.owner (or $repo.name $repo.path) $dqf $dqb -}}
  {{- $nameFormat := printf "%s-%s .head_short_sha_7 %s-%s .number %s-%s" $repo.name $dqf $dqb $dqf $dqb $name -}}
  {{- $label := coalesce $github.label $globals.label -}}
  {{- $project := and $.Values.project $.Values.project.enabled | ternary $name "default" -}}
{{- include "chart.applicationTemplate" (dict "repo" $repo "globals" $globals "server" $server "retryBackoffDuration" $retryBackoffDuration "project" $project "repoURL" $repoURL "label" $label "path" $github.path "nameFormat" $nameFormat "externalLink" $externalLink "infoKey" "pull_request") }}
{{- end }}
{{- end }}
