{{- if and .Values.project .Values.project.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
  annotations:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: '{{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}'
spec:
  description: {{ printf "Project %s" .Values.name }}
  permitOnlyProjectScopedClusters: {{ .Values.project.permitOnlyProjectScopedClusters | default "false" }}
  clusterResourceBlacklist:
    {{- toYaml .Values.project.clusterResourceBlacklist | nindent 4 }}
  clusterResourceWhitelist:
   {{- toYaml .Values.project.clusterResourceWhitelist | nindent 4 }}
  destinations:
    {{- toYaml .Values.project.destinations | nindent 4 }}
  namespaceResourceBlacklist:
    {{- toYaml .Values.project.namespaceResourceBlacklist | nindent 4 }}
  namespaceResourceWhitelist:
    {{- toYaml .Values.project.namespaceResourceWhitelist | nindent 4 }}
  orphanedResources:
    {{- toYaml .Values.project.orphanedResources | nindent 4 }}
  syncWindows:
    {{- toYaml .Values.project.syncWindows | nindent 4 }}
  sourceRepos:
    {{- toYaml .Values.project.sourceRepos | nindent 4 }}
  roles:
    {{- toYaml .Values.project.roles | nindent 4 }}
{{- end }}
