apiVersion: v2
name: argocd-applicationsets-services
description: A HELM Chart for ArgoCD ApplicationSets for Kubernetes
type: application
version: 0.1.2
appVersion: 1.23.0
kubeVersion: ">= 1.23"
home: https://github.com/saidsef/argocd-applicationsets-services
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
  - argoproj
  - argocd
  - gitops
  - applicationsets
maintainers:
  - name: Said Sef
    email: saidsef@gmail.com
sources:
  - https://github.com/saidsef/argocd-applicationsets-services.git
annotations:
  artifacthub.io/changes: |
    - [Added] ArgoCD ApplicationSet Services
    - [Added] GitHub Workflows
