apiVersion: v2
name: argocd-applicationsets-services
description: A HELM Chart for ArgoCD ApplicationSets for Kubernetes
type: application
version: &version "0.4.3"
appVersion: *version
kubeVersion: ">= 1.23"
home: https://github.com/saidsef/argocd-applicationsets-services
icon: https://raw.githubusercontent.com/argoproj/argo/master/docs/assets/argo.png
keywords:
  - argoproj
  - argocd
  - gitops
  - applicationsets
  - argocd-applicationsets
  - preview-environment
maintainers:
  - name: saidsef
    url: https://saidsef.github.io/argocd-applicationsets-services
sources:
  - https://github.com/saidsef/argocd-applicationsets-services.git
annotations:
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/changes: |
    - "Remove kustomize patches or patchesJson6902 section as they are not supported in ArgProj: https://argo-cd.readthedocs.io/en/stable/user-guide/kustomize/"
  artifacthub.io/links: |
    - name: README
      url: https://raw.githubusercontent.com/saidsef/argocd-applicationsets-services/main/README.md
    - name: LICENSE
      url: https://raw.githubusercontent.com/saidsef/argocd-applicationsets-services/main/LICENSE.md
    - name: CONTRIBUTING
      url: https://raw.githubusercontent.com/saidsef/argocd-applicationsets-services/main/CONTRIBUTING.md
