name: Charts

on: [push, pull_request, workflow_dispatch]

jobs:
  chart:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' || contains(github.ref, 'main') }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.4.0
      - name: Setup Chart Linting
        if: ${{ github.event_name == 'pull_request' }}
        id: lint
        uses: helm/chart-testing-action@v2.2.1
      - name: Run chart-testing (list-changed)
        if: ${{ github.event_name == 'pull_request' }}
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - name: Run chart-testing (lint)
        if: ${{ github.event_name == 'pull_request' }}
        run: ct lint --target-branch ${{ github.event.repository.default_branch }} --validate-maintainers=false
      - name: Configure Git
        if: ${{ contains(github.ref, 'main') }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        if: ${{ contains(github.ref, 'main') }}
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: charts
          config: charts/cr.yml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  auto-approve:
    runs-on: ubuntu-latest
    needs: [chart]
    if: ${{ github.event_name == 'pull_request' }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
