name: pre-commit

on: [push, pull_request, workflow_dispatch]

permissions: read-all

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: actions/setup-python@v6
    - uses: terraform-linters/setup-tflint@v6
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: "-a"
